### ISSUE TITLE
Does this work / how to use?

### ISSUE THREAD

**Issue by xklob** [dags-/BlockScraper#1]
Hey, no noob to the standard mod scraper provided with Dynmap, but as it doesn't wokr with 1.10, I'm trying to get this to work. Doesn't seem to have to created a folder; any instructions?

**Comment by xklob** [comment]
Ah, figured it out. It's a server mod, not a client mod like the original DynmapModScraper. You can close this, but I'd suggest adding that info to the readme.

**Comment by dags-** [comment]
thanks, added a little more info to the readme
